// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbyktrpgtcvgnxodkzya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpieWt0cnBndGN2Z254b2RrenlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDIwNzksImV4cCI6MjA2ODIxODA3OX0.5ovGFRW20S-6ettSixkpsYD4yAkudd0LlqmG4HAOWJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});